server:
  port: 8848
  servlet:
    context-path: /
spring:
  application:
    name: community_system
  profiles:
    active: dev
  # 邮件发送
  mail:
    host: smtp.163.com
    username: testlv@163.com
    password: YWFDUCBMLKEFTWMF
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            enable: true
          starttls:
            enable: true
            required: true
  # json时间格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
  # redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
    database: 0

  mvc:
    throw-exception-if-no-handler-found: true
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # xml返回数据为map类型时，空值的key也要显示出来
    call-setters-on-nulls: true
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#配置knife4j配置
knife4j:
  # 是否开启生产环境保护策略,  默认false
  production: false
  # 对Knife4j提供的资源提供BasicHttp校验,保护文档
  #  basic:
  #    # BasicHttp功能 true开启 false关闭  默认false
  #    enable: true
  #    username: admin
  #    password: admin
  #  #自定义文档集合，该属性是数组
  #  documents:
  #    -
  #      # 所属分组
  #      group: 1.2.x
  #      # 类似于接口中的tag,对于自定义文档的分组
  #      name: 测试自定义标题分组
  #      # markdown文件路径,可以是一个文件夹
  #      locations: classpath:author/*
  #  # 是否开启一个默认的跨域配置,该功能配合自定义Host使用  默认false
  #  cors: false
  # 前端Ui的个性化配置属性
  setting:
    # 调试Tab是否显示AfterScript功能,默认开启 默认true
    enableAfterScript: true
    # 是否显示界面中SwaggerModel功能  默认true
    enableSwaggerModels: true
    # 重命名SwaggerModel名称 默认Swagger Model
    swaggerModelName: 映射实体
    # 是否显示界面中"文档管理"功能  默认true
    enableDocumentManage: true
    # 是否在每个Debug调试栏后显示刷新变量按钮,默认不显示  默认false
    enableReloadCacheParameter: true
    # 是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点  默认false
    enableVersion: true
    # 是否开启请求参数缓存 默认true
    enableRequestCache: true
    # 针对RequestMapping的接口请求类型,在不指定参数类型的情况下,如果不过滤,默认会显示7个类型的接口地址参数,如果开启此配置,默认展示一个Post类型的接口地址 默认false
    enableFilterMultipartApis: false
    # 具体接口的过滤类型 默认POST
    enableFilterMultipartApiMethodType: POST
    #Ui默认显示语言,目前主要有两种:中文(zh-CN)、英文(en-US) 默认zh-CN
    language: zh-CN
  enable: true
#    # 是否启用Host  默认false
#    enableHost: false
#    # 启用Host后的地址 默认空
#    enableHostText: http://localhost:8081
lvyx:
  shiro:
    jwt:
      # 是否仅运行使用jwt方式登录
      is-only-jwt: true
    online: 3 # 支持最多三台设备登录
  active: test


